metadata:
  creationTimestamp: "2025-04-03T07:39:54Z"
  generation: 1
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:clusterResourceWhitelist: {}
        f:destinations: {}
        f:sourceRepos: {}
      f:status: {}
    manager: argocd-server
    operation: Update
    time: "2025-04-03T07:39:54Z"
  name: default
  namespace: argocd
  resourceVersion: "597842"
  uid: 0723a156-2ba7-49bd-a77d-ebac604445d5
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'default'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
status: {}
